export const FETCH_SPRINT_BOARD = "FETCH_SPRINT_BOARD";
export const UPDATE_SPRINT_BOARD_LIST = "UPDATE_SPRINT_BOARD_LIST";
export const FETCH_SPRINT_BOARD_ERROR = "FETCH_SPRINT_BOARD_ERROR";
export const FETCH_SPRINT_BOARD_SECTION = "FETCH_SPRINT_BOARD_SECTION";
export const UPDATE_SPRINT_BOARD_SECTION_LIST = "UPDATE_SPRINT_BOARD_SECTION_LIST";
export const FETCH_SPRINT_BOARD_SECTION_ERROR = "FETCH_SPRINT_BOARD_SECTION_ERROR";
export const SET_SNACKBAR_MESSAGE = "SET_SNACKBAR_MESSAGE";
export const REMOVE_SNACKBAR_MESSAGE = "REMOVE_SNACKBAR_MESSAGE";